# Generated by Django 2.2.11 on 2020-04-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_chapter', models.CharField(max_length=3)),
                ('chapter_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberFName', models.CharField(max_length=35)),
                ('memberMidInitial', models.CharField(max_length=1)),
                ('memberLName', models.CharField(max_length=35)),
                ('memberAdmissionDate', models.DateField(verbose_name='Admitted on:')),
                ('memberGender', models.CharField(max_length=1)),
                ('MemberMaritalStatus', models.CharField(choices=[('MR', 'Married'), ('W', 'Widowed'), ('S', 'Single')], default='MR', max_length=2)),
                ('memberInPadSocial', models.BooleanField()),
                ('dateAdmitted', models.DateField()),
                ('MemberCellPhone', models.CharField(max_length=12)),
                ('memberHomePhone', models.CharField(max_length=12)),
                ('memberAddress', models.TextField()),
                ('memberCity', models.CharField(max_length=100)),
                ('memberState', models.CharField(max_length=100)),
                ('memberZip', models.CharField(max_length=6)),
            ],
        ),
    ]
